version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
    volumes:
      - ./:/app/backend/data
    network_mode: host
    restart: always
